SSID = 'Twilio SSID key from Twilio Account Dashboard'
AUTH_TOKEN = 'Authorization Token Number from Twilio Account Dashboard'
FROM_NUMBER = 'Phone number generated by Twilio on the Account Dashboard'
TO_NUMBER = 'Phone number on which the SMS wants to be received on'
API_KEY = 'API Key of Microcontroller Device'
DEVICE_ID = 'Device ID of the microcontroller'
FRAME_SIZE = 10 #can be altered
MUL_FACTOR = 3 #can be altered
